- name: "Include {{ ansible_os_family }} Vars"
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Ensure necessary packages are installed.
  yum:
    name: "{{ packages }}"
    state: present

# Fix slow DNS.
- name: Fix slow DNS (adapted from Bento).
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present

- name: Restart network service (RHEL < 8).
  service: name=network state=restarted
  when: ansible_distribution_major_version < '8'

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

# Cleanup tasks.
- name: Remove unneeded packages.
  yum:
    name:
      - cpp
      - kernel-devel
      - kernel-headers
    state: absent

- name: Clean up yum.
  command: >
    yum clean all
    warn=false
  changed_when: true

- name: Remove RedHat interface persistence (step 1).
  command: >
    rm -f /etc/udev/rules.d/70-persistent-net.rules
    warn=false
  tags: ['skip_ansible_lint']

- name: Remove RedHat interface persistence (step 2).
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^HWADDR'
    - '^UUID'
